### ISSUE TITLE
Build errors with RTI Connext 6.0.0

### ISSUE THREAD

**Issue by slietzau** [rticommunity/ros-data-types#1]
Hey guys,

I just found this awesome project and had some issues building with the latest RTI Connext DDS 6.0.0.

It looks like the `-stl` command was removed and the `-stl` behavior is not the default. As a result the files generated by rtiddsgen don't match the files expected to be generated by the build system.

Additionally I had a problem with namespaces. I had to manually add `-namespace` to the generation command line, otherwise Visual Studio 2017 was reporting that the value FIXED (an enum value) was already defined somewhere else. Turning namespaces on fixed this because the enum value is generated into a namespace.

I just wanted to let you guys know, so this can be fixed in upstream.

**Comment by fercsrti77** [comment]
Hi,

You can go back to the old behavior and generate code with the old mapping by using the command-line option -legacyPlugin.

Thanks for the feedback on the -namespace.

- Fernando

**Comment by slietzau** [comment]
Thank you very much for the quick answer.

I totally overlooked the command line option `-legacyPlugin`. That could work, however this would also require modifying files in `resources/cmake`. So I guess the correct fix would be to add `-legacyPlugin` in case STL containers are turned off instead of changing the default behavior for Connext 6.0.0?

Side question regarding STL containers: Is the STL container option exposed as an option in CMake? I haven't found it a switch to turn on STL containers for the files generated by `connextdds_generate_ros_dds_types`.

For reference, I'm using CMake's `FetchContent` to download this project at configure time and make it available in my project. That means it's rather inconvenient to apply changes to the source code.

**Comment by Antoniolm** [comment]
Hi @slietzau,

Sorry for my delay.

We have the solution to build the project using RTI Connext DDS 6.0.0. If you want to test it before we make the merge to master you can find it in the branch [feature/1](https://github.com/rticommunity/ros-data-types/tree/feature/1) 

Thanks for your feedback!

**Comment by Antoniolm** [comment]
Hi @slietzau,

The branch feature/1 was already merged to master. Please give it a try and let me know how it goes.

**Comment by slietzau** [comment]
Hi @Antoniolm,

thank you very much for the update!
I will have a look and see if it works.
